version: "3.9"

services:
  pg_db:
    container_name: pg_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=Admin
    image: postgres:13.7-alpine3.16
      
      

