CREATE TABLE product (
  id SERIAL NOT NULL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  model VARCHAR(255) NOT NULL,
  color VARCHAR(255) NOT NULL,
  year INT NOT NULL,
  customId VARCHAR NOT NULL UNIQUE
)